---
kind: pipeline
type: docker
name: Build and push image

# anchors:
#   whenOnMasterPush: &onMasterPush
#     branch:
#     - feature/DIGAUS-17
#     event:
#     - push

platform:
  os: linux
  arch: amd64

steps:
- name: environment
  image: 101433154256.dkr.ecr.ap-southeast-2.amazonaws.com/nutrien/environment
  pull: never
  privileged: true
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  when:
    branch:
    - feature/DIGAUS-17
    event:
    - push

- name: build-docker-image
  image: 101433154256.dkr.ecr.ap-southeast-2.amazonaws.com/nutrien/build-container
  pull: never
  privileged: true
  settings:
    use_cache: false
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  when:
    branch:
    - feature/DIGAUS-17
    event:
    - push

- name: push-docker-image
  image: 101433154256.dkr.ecr.ap-southeast-2.amazonaws.com/nutrien/publish-container
  pull: never
  privileged: true
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  when:
    branch:
    - feature/DIGAUS-17
    event:
    - push

# - name: update-cd-repo-triggering-dev-deployment
#   image: nutrien/update-cd-repo-helm-values
#   pull: never
#   privileged: true
#   settings:
#     git_repo: github.com/Agrium/digital-helm-charts.git
#     helm_values_file_name_strategy: suffix
#     helm_values_file_sub_directory: core-auth
#   when: *onMasterPush

trigger:
  event:
  - push
  # - pull_request
  ref:
  - refs/heads/feature/DIGAUS-17
  # - refs/pull/*/head

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

...
