steps:

  - label: ':docker: Build Container'
    command: './.buildkite/deploy.sh build_image'
    agents:
      queue: "buildkite-agent-sandbox-au"
      
  - wait

  - label: ':rocket: Publish Container'
    command: './.buildkite/deploy.sh publish_image'
    agents:
      queue: "buildkite-agent-sandbox-au"

  - wait

  - label: ':helm: Update Helm Charts'
    command: './.buildkite/deploy.sh update_helm_charts'
    env:
      GIT_REPO: git@github.com:Nutrien/digital-helm-charts.git
      ENV: dev
      HELM_VALUES_FILE_NAME_STRATEGY: suffix
      HELM_VALUES_FILE_SUB_DIRECTORY: au-hello-ag
    agents:
      queue: "buildkite-agent-sandbox-au"