steps:

  - name: "::node: Docker Build and Test"
    command: |
    - "npm ci"
    - "npm run test:coverage"
    - "npm run build"
    plugins:
      - docker-compose#v3.0.3:
          run: app

  # - label: ':docker: Build Container'
  #   command: './.buildkite/deploy.sh build_image'
  #   agents:
  #     queue: "buildkite-agent-sandbox-au"
      
  # - wait

  # - label: ':rocket: Publish Container'
  #   command: './.buildkite/deploy.sh publish_image'
  #   agents:
  #     queue: "buildkite-agent-sandbox-au"

  # - wait

  # - label: ':helm: Update Helm Charts'
  #   command: './.buildkite/deploy.sh update_helm_charts'
  #   env:
  #     GIT_REPO: github.com/Nutrien/digital-helm-charts.git
  #     GIT_HTTPS_USERNAME: shyamalarora
  #     ENV: dev
  #     HELM_VALUES_FILE_NAME_STRATEGY: suffix
  #     HELM_VALUES_FILE_SUB_DIRECTORY: au-hello-ag
  #   agents:
  #     queue: "buildkite-agent-sandbox-au"