steps:

  - label: ':docker: Build Container'
    command: './.buildkite/deploy.sh build_image'
    agents:
      queue: "buildkite-agent-sandbox-au"
      
  - wait

  - label: ':docker: Publish Container'
    command: './.buildkite/deploy.sh publish_image'
    agents:
      queue: "buildkite-agent-sandbox-au"